### ISSUE TITLE
flat model or spherical model?

### ISSUE THREAD

**Issue by lynlyf** [ziyixi/pyfk#12]
Hi, Ziyi,

Zhu's FK code is for flat-layered model.

pyfk is valid for flat layers or spherical model or both?

**Comment by ziyixi** [comment]
Hello,

Thanks for asking the question! Both FK and PyFK support flattening the spherical Earth to be flat. So in theory it's still for flat-layered models but has the ability to handle the spheric model (though might not be accurate). 

You can refer to the [tutorial](https://ziyixi.science/pyfk/introduction/tutorial.html) and search "flattening" if interested.

**Comment by lynlyf** [comment]
thanks for clarity.
