### ISSUE TITLE
Changing 1D Earth Model

### ISSUE THREAD

**Issue by snoltcaraway** [ziyixi/pyfk#13]
Is there a way to change the initial 1D earth model? I see that there is an option to use prem, ak135 no mud ,and 1066a in the test_taup.py file. However, I am interested in using a single layer model at first. Is there a way to change how many layers prem uses or import my own velocities?

**Comment by ziyixi** [comment]
Hi, it's a good question! I believe we can use a Numpy array to initialize the model. You may see `prem_data = TestFunctionTaup.gen_test_model("prem")` in the tutorial, but the `prem_data` is just a Numpy array. 

This array should have the same format as FK, ideally, if you use `numpy.loadtxt` to load the FK's model file, it should get the same result. For your question, if you want to test only one layer, maybe you can initialize the array with only one row?

**Comment by snoltcaraway** [comment]
Thank you! I just created a np.array[] with my desired values, and commented out the prem_data = TestFunctionTaup.gen_test_model("prem").

I was also wondering about setting the distances. I see we can change the distances to whatever we want, but is there a way to also set the azimuth? For example, if I want to put in an array that covers 20 degrees at varying distances from the azimuth. 

I also see that in config_prem_static theres a line that is receiver_distance=np.arange()). I am not sure what this line is doing. I understand np.arange, but we set distances earlier and set them again in the static?

**Comment by ziyixi** [comment]
The configuration of the azimuth is done when setting the source. If you check the source configuration class, there should be an azimuth over there. This setting is also the same as FK, as the Green functions there also don't contain the azimuth information.

`config_prem_static` is only about calculating the zero-frequency displacement and generally are not related to calculating the waveform. You may safely ignore that part.

**Comment by snoltcaraway** [comment]
I see that I can set my source mechanism from my gcmt file, which I have done. In its input, I have a lat, lon for the source. Is there anyway I can input lat,lon for the receivers? I am not seeing how to change the azimuthal coverage for the receivers. 

Do I set different azimuths per this section of the package? az = 20 in my config parameters? (20 degrees from earthquake source)

def calculate_radiation_pattern(self, az: float) -> None:
        """
        calculate the radiation pattern 3*3 array

        :param az: station azimuth in degree measured from the North (clockwise)
        :type az: float
        :raises PyfkError: length of source_mechanism must be 1, 3, 4, 7

**Comment by ziyixi** [comment]
As the PyFK is a 1D package, I think the location for the source (lat, lon) will be ignored when you are using a GCMT file. And there is also no way to specify the lat/lon for the stations.

I personally suggest you consider using the distance calculation function in `Obspy`, such as `obspy.geodetics.base.gps2dist_azimuth` to convert the coordinates to the distance. 

And you might need to create different azimuths if you have different stations. I believe they will have different radiation patterns, and that's the reason why the source class needs to be initialized independently.

**Comment by snoltcaraway** [comment]
I understand, thank you!

**Comment by snoltcaraway** [comment]
I can change the azimuth here sync_result = calculate_sync(gf, config_prem, 30, source_time_function)

The 30 represents the az, degree from the station starting from North. 

I apologize for the confusion! You have been a great help.
