### ISSUE TITLE
Unit of Green functions calculated by pyfk.gf.gf.calculate_gf.

### ISSUE THREAD

**Issue by VioletaSeo** [ziyixi/pyfk#3]
While using `calculate_gf` to compute the GFs, I became confused about the unit of results. As described in the API reference, the resulting GFs should be displacements in cm. However, while comparing those with the results computed from the modules of Computer Programs in Seismology (CPS) (http://www.eas.slu.edu/eqc/eqc_cps/TUTORIAL/GREEN/index.html), I suspected that they were actually velocities, not displacements. In fact, by integrating GFs produced by `calculated_GF`, their shapes become identical to those computed from CPS modules.

Actually, original `fk` seems to suffer from the identical problem as described in the "Output type" section of https://blog.seisman.info/fk-notes/#%E8%BE%93%E5%87%BA%E7%B1%BB%E5%9E%8B. I don't know if it is intentional, but I think their should be some modifications either in the manual or the program. 

```
Output type
fkWhat physical quantity is the calculated Green's function? Is it displacement or velocity?

In Zhu and Rivera (2002) article, comments in the code and documentation such as multiple locations mentioned fk is calculated displacement amount, in fact, use fkand synsynthetic seismograms are calculated velocity field.

Zhu and Rivera (2002) Appendix B gives the source term corresponding to different source types and different m values, where the source term represents the displacement-stress discontinuity caused by the source. The source term is a constant independent of frequency, so the source term used in fk is the pulse source in the time domain. (The pulse function in the time domain is a constant in the frequency domain, so adding a constant source term to the frequency domain in fk is actually equivalent to adding a pulse source to the time domain.)

Therefore, what fk actually calculates is the displacement field corresponding to the pulse source, which is equivalent to the velocity field produced by the step function. (The partial derivative of the step function is the impulse function.)

For a real simple earthquake of small magnitude, the source time function can be considered as a step function, and the partial derivative of the source time function is the impulse function. Thus fk calculated velocity field Green's function in fact, using synthe synthesis of real data, if the -Doption to specify the source of a triangular function (impulse function approximation), are synthesized to obtain velocity data.
```

The figure below shows the ZDD components computed from the same event and sampling interval (pyfk GF was integrated using https://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.integrate.html). As you can see, the shapes are almost identical but while pyfk GF has more features that come later (~3 minutes), CPS GF does not have such features. I am also curious why such differences occur.
The above trace was generated by pyfk and the below trace was generated by CPS.
![캡처17](https://user-images.githubusercontent.com/57863231/108809869-1b42e580-75ed-11eb-9829-0b173d87cfa0.PNG)

**Comment by ziyixi** [comment]
Hi Lucas,

According to Seisman's blog, it seems the unit of FK is the velocity, which is also confirmed by your test. I think it might be better to keep it the same as FK to avoid any confusion.

As for the signals after 3 min, I think it might be some numerical noise. Do you have the setting of pyfk so I can do some tests comparing with FK? I suspect there might be some issue in convolving Green's function with the source time function. According to my experience, when the largest epicenter distance is relatively small, the result might not be accurate, as the wavenumber integration is not accurate.

It is also very strange that at the beginning of the waveform, there is also some signal which is definitely some numerical noise. I don't know if FK has such an issue, which might also need some tests.
