### ISSUE TITLE
ImportError: cannot import name 'SourceModel'

### ISSUE THREAD

**Issue by globaltechinc** [ziyixi/pyfk#6]
I cannot load the package, and always get the same error regardless of if I load different functions. The error is always the same:

> ImportError                               Traceback (most recent call last)
<ipython-input-4-8f4600c18633> in <module>
----> 1 from pyfk import SourceModel, SeisModel, Config
>
>/mnt/c/Users/jwilliams/Documents/GitHub/7151_smart_frac/dev/Synthetic_data_dev/FK/pyfk.py in <module>
     14 
     15 #%%
---> 16 from pyfk import SourceModel, SeisModel, Config
     17 #%%
     18 source_prem = SourceModel(sdep=16.5, srcType="dc")
>
>ImportError: cannot import name 'SourceModel'

**Comment by ziyixi** [comment]
Hello,

It looks to me that there might be some problem in installing pyfk. If you can't import `SourceModel `, maybe directly call `import pyfk` will also give an error here. Are you using `pip install pyfk`? If that's the case, can you try to use `conda -c ziyixi pyfk` to install the package or put the detailed installation log from `pip` here? Thanks.

**Comment by globaltechinc** [comment]
Thank you for your reply.

Yes, I installed it using pip install pyfk, and you are correct. `import pyfk` generates an error. I try to avoid conda because encounter conflicts in the past, and I prefer to use pip, but if that's the way to go then I'll use it.

**Comment by ziyixi** [comment]
I also find there might be some problem installing through pip, such as the Google Colab. I will update the pip package these days to see if there is a more stable way to install it.
