### ISSUE TITLE
Reference information is not available

### ISSUE THREAD

**Issue by wangliang1989** [ziyixi/pyfk#7]
Reference information is not available

**Comment by ziyixi** [comment]
Hi Liang,

What reference information are you talking about? Thanks.

**Comment by wangliang1989** [comment]
就是文献引用

**Comment by ziyixi** [comment]
多谢指出，我最近就把package的reference挂上来，同时打算先把本package先行上传到zenodo上。

**Comment by wangliang1989** [comment]
你论文定了？

**Comment by ziyixi** [comment]
暂时还没写... 打算忙完这阵子就开始做 现在就个AGU的poster

**Comment by wangliang1989** [comment]
论文还没出来，你就开源了

**Comment by ziyixi** [comment]
多谢提醒... 我当时写这个东西的时候也没想太多，就直接放GitHub上了，看来确实得加快进度了。
