### ISSUE TITLE
AttributeError: 'numpy.int64' object has no attribute 'split'

### ISSUE THREAD

**Issue by JandyZ22** [ziyixi/pyfk#8]
I found a new problem in the new virtual environment installed according to the documentation, but it seems to be because obspy and numpy=1.22.3 are not compatible with the problem, numpy will be installed back to the original 1.21.4 on the good.

**Comment by ziyixi** [comment]
Thanks for pointing out the problem! I have also found the same issue in Obspy before but have not recognized it will influence this package. One way to handle this problem on my side is to manually specify the NumPy version, but it might cause some unexpected problems if there are already several installed packages before. I will add this issue to the document.

**Comment by ziyixi** [comment]
Should have been fixed in the latest version.
